[workspace]
members = [
    "domain",
    "application",
    "infrastructure"
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.81"
tokio = { version = "1.39.1", features = ["full"] }
rocket = { version = "0.5.1", features = ["json"] }